{
  "name": "mp3-mp4-downloader",
  "version": "1.0.0",
  "type": "module",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.18.2",
    "uuid": "^9.0.0",
    "yt-dlp-exec": "^2.0.2"
  }
}
